//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amendis2.Admin
{


    public partial class modify_userRoles
    {
        protected global::System.Web.UI.WebControls.DropDownList UserDropDownList;
        protected global::System.Web.UI.WebControls.ListBox RolesListBox;
        protected global::System.Web.UI.WebControls.Button LoadRolesButton;
        protected global::System.Web.UI.WebControls.Button AddRoleButton;
        protected global::System.Web.UI.WebControls.Button RemoveRoleButton;
        protected global::System.Web.UI.WebControls.Label StatusMessageLabel;
    }
}
