//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amendis2.Admin
{


    public partial class modify_userRoles
    {
        protected global::System.Web.UI.WebControls.Panel UserDetailsPanel;
        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
        protected global::System.Web.UI.WebControls.DropDownList UserDropDownList;
        protected global::System.Web.UI.WebControls.TextBox SearchTextBox;
        protected global::System.Web.UI.WebControls.CheckBoxList RolesCheckBoxList;
        protected global::System.Web.UI.WebControls.Button AddRoleButton;
        protected global::System.Web.UI.WebControls.Button RemoveRoleButton;
        protected global::System.Web.UI.WebControls.Label StatusMessageLabel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dynamicList;
        protected global::System.Web.UI.WebControls.TextBox txtInput;
        protected global::System.Web.UI.WebControls.Button btnSubmit;

    }
}
